services:
  traefik:
    image: ${TRAEFIK_IMAGE:-traefik:latest}
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    volumes:
      - ${MYDATA}/letsencrypt:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic_conf.yml:/dynamic_conf.yml
      - ./traefik/users.htpasswd:/users.htpasswd
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--ping"
      - "--providers.docker.network=web"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic_conf.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web-admin.address=:8443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=${MYMAIL}"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
      #- --certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
    labels:
      - "traefik.enable=true"
      # To Fix enable dashboard on port 8443
      - "traefik.http.routers.dashboard.entrypoints=web-admin"
      - "traefik.http.routers.dashboard.rule=Host(`${MYDOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      # - "traefik.http.routers.dashboard.rule=Host(`traefik.${MYDOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/users.htpasswd"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  sharelatex:
    restart: always
    image: ${OVERLEAF_IMAGE:-ldap-overleaf-sl:5.5.8}
    build:
      context: ./ldap-overleaf-sl
      args:
        login_text: ${LOGIN_TEXT:-username}
        collab_text: ${COLLAB_TEXT:-Direct sharing with collaborators is enabled for activated users.}
        admin_is_sysadmin: ${ADMIN_IS_SYSADMIN:-false}
        TEXLIVE_REPOSITORY: ${TEXLIVE_REPOSITORY:-https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2025/tlnet-final}
    depends_on:
      mongo:
        condition: service_healthy
      mongoinit:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      traefik:
        condition: service_started
    privileged: false
    networks:
      - web
    expose:
      - 80
      - 443
    volumes:
      - ${MYDATA}/sharelatex:/var/lib/overleaf
    labels:
      - "traefik.enable=true"
      # handle https traffic
      - "traefik.http.routers.sharel-secured.rule=Host(`${MYDOMAIN}`)"
      - "traefik.http.routers.sharel-secured.tls=true"
      - "traefik.http.routers.sharel-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.sharel-secured.entrypoints=web-secure"
      - "traefik.http.middlewares.sharel-secured.forwardauth.trustForwardHeader=true"
      # Docker loadbalance
      - "traefik.http.services.sharel.loadbalancer.server.port=80"
      - "traefik.http.services.sharel.loadbalancer.server.scheme=http"
      - "traefik.http.services.sharel.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.sharel.loadbalancer.sticky.cookie.name=io"
      - "traefik.http.services.sharel.loadbalancer.sticky.cookie.httponly=true"
      - "traefik.http.services.sharel.loadbalancer.sticky.cookie.secure=true"
      - "traefik.http.services.sharel.loadbalancer.sticky.cookie.samesite=lax"

    environment:
      OVERLEAF_APP_NAME: Overleaf
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_SITE_URL: https://${MYDOMAIN}
      OVERLEAF_NAV_TITLE: Overleaf - run by ${MYDOMAIN}
      #OVERLEAF_HEADER_IMAGE_URL: https://${MYDOMAIN}/logo.svg
      OVERLEAF_ADMIN_EMAIL: ${MYMAIL}
      OVERLEAF_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"} ]'
      OVERLEAF_RIGHT_FOOTER: '[{"text": "LDAP Overleaf (beta)"} ]'
      OVERLEAF_EMAIL_FROM_ADDRESS: "noreply@${MYDOMAIN}"
      OVERLEAF_EMAIL_SMTP_HOST: ${OVERLEAF_EMAIL_SMTP_HOST:-smtp.${MYDOMAIN}}
      OVERLEAF_EMAIL_SMTP_PORT: ${OVERLEAF_EMAIL_SMTP_PORT:-587}
      OVERLEAF_EMAIL_SMTP_SECURE: ${OVERLEAF_EMAIL_SMTP_SECURE:-false}
      OVERLEAF_EMAIL_SMTP_USER: ${OVERLEAF_EMAIL_SMTP_USER:-}
      OVERLEAF_EMAIL_SMTP_PASS: ${OVERLEAF_EMAIL_SMTP_PASS:-}
      # OVERLEAF_EMAIL_SMTP_USER:
      # OVERLEAF_EMAIL_SMTP_PASS:
      # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
      # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
      OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by ${MYDOMAIN} - please contact ${MYMAIL} if you experience any issues."

      # make public links accessible w/o login (link sharing issue)
      # https://github.com/overleaf/docker-image/issues/66
      # https://github.com/overleaf/overleaf/issues/628
      # https://github.com/overleaf/web/issues/367
      # Fixed in 2.0.2 (Release date: 2019-11-26)
      OVERLEAF_ALLOW_PUBLIC_ACCESS: "true"
      OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: "true"

      OVERLEAF_SECURE_COOKIE: "true"
      OVERLEAF_BEHIND_PROXY: "true"

      ALLOW_EMAIL_LOGIN: ${ALLOW_EMAIL_LOGIN:-true}
      ALLOW_LDAP_LOGIN: ${ALLOW_LDAP_LOGIN:-true}
      LDAP_SERVER: ${LDAP_SERVER:-}
      LDAP_BASE: ${LDAP_BASE:-}
      LDAP_BINDDN: ${LDAP_BINDDN:-}
      LDAP_BIND_USER: ${LDAP_BIND_USER:-}
      LDAP_BIND_PW: ${LDAP_BIND_PW:-}
      LDAP_SERVER_CACERT: ${LDAP_SERVER_CACERT:-}
      LDAP_USER_FILTER: ${LDAP_USER_FILTER:-}
      LDAP_ADMIN_GROUP_FILTER: ${LDAP_ADMIN_GROUP_FILTER:-}
      LDAP_CONTACT_FILTER: ${LDAP_CONTACT_FILTER:-}
      LDAP_CONTACTS: ${LDAP_CONTACTS:-false}

      OAUTH2_ENABLED: ${OAUTH2_ENABLED:-false}
      OAUTH2_PROVIDER: ${OAUTH2_PROVIDER:-OAuth}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID:-}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET:-}
      OAUTH2_SCOPE: ${OAUTH2_SCOPE:-openid profile email}
      OAUTH2_AUTHORIZATION_URL: ${OAUTH2_AUTHORIZATION_URL:-}
      OAUTH2_TOKEN_URL: ${OAUTH2_TOKEN_URL:-}
      OAUTH2_TOKEN_CONTENT_TYPE: ${OAUTH2_TOKEN_CONTENT_TYPE:-application/x-www-form-urlencoded}
      OAUTH2_PROFILE_URL: ${OAUTH2_PROFILE_URL:-}
      OAUTH2_USER_ATTR_EMAIL: ${OAUTH2_USER_ATTR_EMAIL:-email}
      OAUTH2_USER_ATTR_UID: ${OAUTH2_USER_ATTR_UID:-sub}
      OAUTH2_USER_ATTR_FIRSTNAME: ${OAUTH2_USER_ATTR_FIRSTNAME:-given_name}
      OAUTH2_USER_ATTR_LASTNAME: ${OAUTH2_USER_ATTR_LASTNAME:-family_name}
      OAUTH2_USER_ATTR_IS_ADMIN: ${OAUTH2_USER_ATTR_IS_ADMIN:-}

      # Same property, unfortunately with different names in
      # different locations
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      ENABLED_LINKED_FILE_TYPES: "url,project_file"

      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: "true"

  mongo:
    restart: always
    image: mongo:${MONGO_VERSION:-6.0}
    container_name: mongo
    expose:
      - 27017
    volumes:
      - ${MYDATA}/mongo_data:/data/db
    healthcheck:
      #test: "mongosh --quiet --eval 'rs.hello().setName ? rs.hello().setName : rs.initiate({_id: \"overleaf\",members:[{_id: 0, host:\"mongo:27017\"}]})'"
      test: ["CMD", "mongosh", "--quiet", "--eval", "quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - web
    command: "--replSet overleaf"

  mongoinit:
    image: mongo:${MONGO_VERSION:-6.0}
#    # this container will exit after executing the command
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      [
        "mongosh",
        "--host",
        "mongo:27017",
        "--eval",
        'try { rs.status() } catch (error) { if (error.code !== 94) throw error; const result = rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] }); if (!result.ok) throw new Error(result.errmsg); }',
      ]
    networks:
      - web

  redis:
    restart: always
    image: redis:6.2
    command: ["redis-server", "--appendonly", "${REDIS_AOF:-no}"]
    container_name: redis
    # modify to get rid of the redis issue #35 and #19 with a better solution
    # WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128.
    # for vm overcommit: enable first on host system
    # sysctl vm.overcommit_memory=1 (and add it to rc.local)
    # then you do not need it in the redis container
    sysctls:
      - net.core.somaxconn=65535
      # - vm.overcommit_memory=1
    expose:
      - 6379
    volumes:
      - ${MYDATA}/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

networks:
  web:
    external: true
